server:
  port: 8001
  
eureka:
  instance:
    hostname: localhost
    status-page-url: http://${eureka.instance.hostname}:${server.port}/index
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/